Error generating article for "The Justice Department is about to make its case for a Google breakup. Here's what to know": Error: Failed to generate article content
    at generateArticleContent (file:///opt/render/project/src/dist/index.js:266:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async generateNewsArticle (file:///opt/render/project/src/dist/index.js:597:41)
    at async scrapeAndGenerateNews (file:///opt/render/project/src/dist/index.js:621:59)
Error creating article for headline "The Justice Department is about to make its case for a Google breakup. Here's what to know": Error: Failed to generate article content
    at generateArticleContent (file:///opt/render/project/src/dist/index.js:266:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async generateNewsArticle (file:///opt/render/project/src/dist/index.js:597:41)
    at async scrapeAndGenerateNews (file:///opt/render/project/src/dist/index.js:621:59)
Initial news scraping complete. Created 0 articles.
11:32:14 PM [express] GET /api/articles/featured 500 in 133162ms :: {"message":"Failed to fetch featuâ€¦
11:32:26 PM [express] GET /api/user 401 in 0ms :: {"error":"Not authenticated"}
Login error: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://dpg-d02nijeuk2gs73em5tig-a.oregon-postgres.render.com/v2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ETIMEDOUT 35.227.164.209:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '35.227.164.209',
    port: 443
  },
  [Symbol(kMessage)]: 'connect ETIMEDOUT 35.227.164.209:443'
}
11:32:27 PM [express] POST /api/login 500 in 133632ms :: {"error":"Internal server error"}
11:32:27 PM [express] GET /api/user 401 in 0ms :: {"error":"Not authenticated"}
11:32:29 PM [express] GET /api/user 401 in 1ms :: {"error":"Not authenticated"}